apiVersion: v2
name: k8s-monitoring
description: Helm chart for k8s cluster monitoring with VictoriaMetrics and Grafana
type: application
version: 0.1.0
dependencies:
  - name: victoria-metrics-cluster
    version: 0.14.12
    repository: https://victoriametrics.github.io/helm-charts/
  - name: victoria-metrics-agent
    version: 0.14.8
    repository: https://victoriametrics.github.io/helm-charts/
  - name: grafana
    version: 8.6.0
    repository: https://grafana.github.io/helm-charts